##############################################################################
# Pynsour Sample Configuration File
##############################################################################


##############################################################################
# Global Settings
##############################################################################

name: pynsour
version: 1
nicks:
 - pybot1
 - pybot2

##############################################################################
# Connections
##############################################################################
# pynsour conf version 1 only supports a single connection! agh!

connections:
- name: example.org
  hostname: irc.example.org
  port: 6667
  username: joeuser
  realname: "Joe User"
  nicks:
  - expybot1
  - expybot2

##############################################################################
# Handlers
##############################################################################

# Channel paths are formed as: "example.org/#pynsour"
handlers:
- channel: "(.*)/#(.*)"
  script: \2.py
